main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [RustyTrumbone]
depend: [MassiveCore, Factions]

permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  blessedwar.basecommand:   {description: use the Blessed War base command, default: false}
  blessedwar.award:         {description: award a religion, default: false}
  blessedwar.claim:         {description: claim your reward from the Blessed War, default: false}
  blessedwar.end:           {description: end the Blessed War, default: false}
  blessedwar.fac.join:      {description: align your faction with a religion for the Blessed War, default: false}
  blessedwar.fac.leave:     {description: leave the alignment your faction is associated with, default: false}
  blessedwar.modify:        {description: modify an alignment's stat, default: false}
  blessedwar.join:          {description: align yourself with a religion for the Blessed War, default: false}
  blessedwar.leave:         {description: leave the alignment you are associated with, default: false}
  blessedwar.report:        {description: get a report of the Blessed War, default: false}
  blessedwar.start:         {description: start the Blessed War, default: false}
  blessedwar.config:        {description: edit the BlessedWar config, default: false}
  blessedwar.version:       {description: display BlessedWar version, default: false}

# -------------------------------------------- #
# START NOTATION
# -------------------------------------------- #
  blessedwar.*:
    children:
      blessedwar.basecommand: true
      blessedwar.award: true
      blessedwar.claim: true
      blessedwar.end: true
      blessedwar.fac.join: true
      blessedwar.fac.leave: true
      blessedwar.modify: true
      blessedwar.join: true
      blessedwar.leave: true
      blessedwar.report: true
      blessedwar.start: true
      blessedwar.config: true
      blessedwar.version: true


# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  blessedwar.kit.op:
    default: op
    children:
      blessedwar.*: true
  blessedwar.kit.rank3:
    default: false
    children:
      blessedwar.kit.rank2: true
      blessedwar.config: true
      blessedwar.award: true
      blessedwar.end: true
      blessedwar.report: true
      blessedwar.modify: true
      blessedwar.start: true
  blessedwar.kit.rank2:
    default: false
    children:
      blessedwar.kit.rank1: true
  blessedwar.kit.rank1:
    default: false
    children:
      blessedwar.kit.rank0: true
  blessedwar.kit.rank0:
    default: false
    children:
      blessedwar.basecommand: true
      blessedwar.claim: true
      blessedwar.fac.join: true
      blessedwar.fac.leave: true
      blessedwar.join: true
      blessedwar.leave: true
      blessedwar.version: true
  blessedwar.kit.default:
    default: true
    children:
      blessedwar.kit.rank0: true